### ISSUE TITLE
Infinite loop on decode stream

### ISSUE THREAD

**Issue by xocasdashdash** [francoispqt/gojay#84] opened 2018-10-18 14:33 UTC
(Sorry for the empty post, i fat fingered the keyboard)
I've found an issue when I'm decoding an stream where gojay would go into an infinite loop on some chunks of the stream.
The code basically was this:
```go
rawBytes, bufferErr := b.ReadBytes('\n')
entries := 1
breakOut := false
logger.Log.Debug("First line read, going into loop")
//TODO: Review loop code
for (bufferErr == io.EOF || bufferErr == nil) && !readCanceled && !breakOut {
    if len(rawBytes) > 0 {
        logger.Log.Debugf("Going to decode %d bytes", len(rawBytes))
        rawBuffer := bytes.NewBuffer(rawBytes)
        dec := gojay.Stream.BorrowDecoder(rawBuffer)
        
        err := dec.DecodeStream(streamChan)
        if err != nil {
            logger.Log.Errorf("error decoding \"%+v\" %+v", rawBytes, err)
        } else {
            streamChan <- m
        }
        dec.Release()
    }
    rawBytes, bufferErr = b.ReadBytes('\n')
    entries = entries + 1
    logger.Log.Debugf("Read %d bytes", len(rawBytes))
    if len(rawBytes) == 0 {
        if bufferErr == io.EOF {
            breakOut = true
        } else {
            logger.Log.Debug("No data but not at EOF. Error: %+v", bufferErr)
        }
    }
    logger.Log.Debugf("Exit? Err: %+v, RC: %+v, BO: %+v", bufferErr, readCanceled, breakOut)
}
```

Basically some chunks of "rawBuffer" would make the buffer end logic fail on https://github.com/francoispqt/gojay/blob/master/decode.go#L961-L990 and then the loop would get stuck.

I fixed by working with specific messages and putting the messages to a channel myself

**Comment by francoispqt** [comment] 2018-10-27 05:00
Hi, 
The only case is if it constantly reads 0 bytes and doesn't return an error, why would it do that? I'm going to run a few tests to reproduce and try to figure out a solution.

**Comment by francoispqt** [comment] 2019-03-29 16:22
Hi sorry for taking so long to answer your request, I was very busy these past few months. So the bug you mentioned is fixed, it was a problem when the buffer was reset to 0 and wouldn't grow anymore. 

Regarding gojay, it's not meant to decode arbitrary JSON, only data implementing the `Unmarshaler` interface, so it won't really be much more performant in your case. 

I'm closing this issue as the problem is fixed.

**Closed by francoispqt** 2019-03-29 16:22 UTC

**Comment by xocasdashdash** [comment] 2019-03-29 17:13
@berglh Sorry, just saw this. I do have those interfaces implemented, but I did not think it was necessary for this issue.
