### ISSUE TITLE
Encoding/Decoding null values

### ISSUE THREAD

**Issue by pierrec** [francoispqt/gojay#39] opened 2018-06-19 18:45 UTC
Hello,

Currently, there is no way to encode or decode a NULL. Is there a reason for this?
Would you mind if it was added?

Thanks.

**Comment by francoispqt** [comment] 2018-06-20 02:19
Hi,

So for encoding null, we (my company) haven't found the need as there are some `OmitEmpty` methods. But we can find a solution. 

For decoding, if we want to check null values we use a pointer, which will be `nil` if value is `null` (I believe the same solution is valid for `encoding/json`), example:
```go
type TestObj struct {
	test *string
}

func (t *TestObj) UnmarshalJSONObject(dec *gojay.Decoder, k string) error {
	switch k {
	case "test":
		return dec.String(t.test)
	}
	return nil
}

func (t *TestObj) NKeys() int {
	return 1
}

json := []byte(`{
    "test": null
}`)

testObj := &TestObj{}
_ = gojay.UnmarshalJSONObject(json, testObj)
fmt.Println(testObj.test == nil) // true
```

I'm ok to add a solution but we should define what we are trying to achieve (encoding null for zero values, or nil pointer, having a nullable type like in SQL). 

Also I'm open to PR so if you know what you want and can implement it without affecting performance then I'd be ok. I'm currently working on a code generator for maps, structs and slices which is almost done (writing tests), so would be happy to have some help.

Thanks

**Comment by pierrec** [comment] 2018-06-20 06:22
Indeed I am fetching/writing data from/to an SQL database that may have nulls. I will submit a PR for encoding asap.
Thanks for the constructive feedback !

**Comment by francoispqt** [comment] 2018-06-24 12:09
I will close the issue, let me know if you need help or suggestion.

**Closed** 2018-06-24 12:09 UTC

**Comment by wvh** [comment] 2018-06-27 13:45
I've got an array with binary values – a UUID. Since it doesn't make sense to encode this array to a JSON array, I call `String()` on it and then encode the string representation to JSON; if it is nil, I write a literal `null` with `AddEmbeddedJSON` so it's clear that it is not set.
```go
null := []byte("null")
enc.AddEmbeddedJSONKey("uid", (*gojay.EmbeddedJSON)(&null))
```

Perhaps it would make sense to add a constant for null to gojay itself to prevent having to create a raw value everywhere one is needed:
```go
var JsonNull = gojay.EmbeddedJSON("null")
```
... or even add a new helper type:
```go
func (*Encoder) AddNull() {}
func (*Encoder) AddNullKey() {}
```
... I suppose there's no point in adding the OmitEmpty variants. :wink:

**Comment by francoispqt** [comment] 2018-07-04 12:44
Sure it does make a lot of sense. You can submit a PR, or I'll add it myself, up to you :) 
Sorry for the delay I was on holiday in a remote area.

**Comment by simpajj** [comment] 2018-08-23 15:08
Hi! Apologies for reopening this one. 

I tried the example above with regards to decoding nil values: 

```go
type TestObj struct {
	test *string
}

func (t *TestObj) UnmarshalJSONObject(dec *gojay.Decoder, k string) error {
	switch k {
	case "test":
		return dec.String(t.test)
	}
	return nil
}

func (t *TestObj) NKeys() int {
	return 1
}

json := []byte(`{
    "test": null
}`)

testObj := &TestObj{}
_ = gojay.UnmarshalJSONObject(json, testObj)
fmt.Println(testObj.test == nil) // true
```

[This panics when the value is not nil](https://gist.github.com/simpajj/f2e578f6069b154e2afbcb3a6f862e2b). Is this intended behavior? I'd expect it to set the value if it exists and otherwise set it to nil.

**Comment by francoispqt** [comment] 2018-08-24 03:36
Will add this during the weekend in a new release:
```go
dec.StringNull(&testObj.test /* **string */) // passing a pointer to a pointer, this way, if your pointer `testObj.test` is nil, it will remain untouched when `null` is encountered. 
// If a non `null` value is encountered, a pointer to a new string will be assigned. 
// If your pointer is non nil, the value will be assigned to it directly.
```
Will add it for all types. For non primitive types, it will be slightly different.

**Comment by simpajj** [comment] 2018-08-24 09:14
Awesome! Thanks for the quick reply and for this great library!

**Comment by francoispqt** [comment] 2018-08-26 12:38
It's almost done for primitive types (just a few tests to write). 

For non primitive types I have tested two solutions and I'd like your point of view. 

- 1st solution, using reflection: 
```go
type ObjNull struct {
	O *ObjNull
}

func (o *ObjNull) UnmarshalJSONObject(dec *gojay.Decoder, k string) error {
	switch k {
	case "o":
		return dec.ObjectNull(&o.O)
	}
	return nil
}

func (o *ObjNullReflect) NKeys() int {
	return 1
}
```

- 2nd solution, without reflection: 
```go
func (o *ObjNull) UnmarshalJSONObject(dec *gojay.Decoder, k string) error {
	switch k {
	case "o":
		return dec.ObjectNull(func() gojay.UnmarshalerJSONObject {
                     o.O = &ObjNull{}
                     return o.O
                })
	}
	return nil
}
```

Performance: 
1st: 
```sh
pkg: github.com/francoispqt/gojay/benchmarks/decoder
BenchmarkJSONDecodeObjNullReflection-8   	 2000000	       924 ns/op	     336 B/op	       6 allocs/op
```
2nd:
```sh
pkg: github.com/francoispqt/gojay/benchmarks/decoder
BenchmarkJSONDecodeObjNullFactory-8   	 2000000	       896 ns/op	     336 B/op	       6 allocs/op
```

The solution without reflection is slightly faster, but for the case of an Array, without reflection will be even faster. 
Also, the solution using reflection will panic the type is not a pointer to a `gojay.UnmarshalerJSONObject` implementation. 
On the other hand, the solution with reflection is more consistent with the solution for primitive types.

Let me know which one seems the best to you. 
Thanks

**Comment by simpajj** [comment] 2018-08-26 16:42
Thanks! The solution without reflection seems clearer to me and personally I'd prefer that one. However, it might make sense to value the consistency of the API above all other concerns right now and with that said, maybe the solution using reflection is the right way to go.

**Comment by francoispqt** [comment] 2018-08-27 15:14
I'll go for the one using reflection (it's really just a tiny bit of reflection). Will publish a new release tomorrow (2018-08-28) including all the null decoding. Thanks!
